language: c
compiler:
  - gcc
before_install:
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
  - tar xzf /tmp/cmake.tar.gz
  - export PATH=$PWD/cmake-3.3.1-Linux-x86_64/bin/:$PATH
  - export LD_LIBRARY_PATH=$PWD/build/dist/lib:$LD_LIBRARY_PATH
  - sudo pip install cpp-coveralls
  - sudo apt-get install libssl-dev
script:
  - mkdir build
  - cd build && cmake .. && make all test
after_success:
  - coveralls --exclude dist --exclude project_cn-cbor-prefix --gcov-options '\-lp'

