language: c
compiler:
  - gcc
before_install:
  - pip install cpp-coveralls --user
  - wget https://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz --no-check-certificate
  - tar xzf /tmp/cmake.tar.gz
  - export PATH=$PWD/cmake-3.3.1-Linux-x86_64/bin/:$PATH
  - export LD_LIBRARY_PATH=$PWD/build/dist/lib:$LD_LIBRARY_PATH

addons:
  apt:
    packages:
    - libssl-dev
script:
  - mkdir build
  - cd build && cmake .. && make all test
  - make coveralls


