language: c
compiler:
  - clang
  - gcc
sudo: false
before_install:
  - pip install cpp-coveralls --user
  - export LD_LIBRARY_PATH=$PWD/build/dist/lib;$LD_LIBRARY_PATH
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
    - libssl-dev
    - cmake
    - cmake-data
script:
  - mkdir build
  - cd build && cmake -D coveralls_send=ON .. && make all test
  - make coveralls


