language: c
compiler:
  - clang
  - gcc
sudo: false
before_install:
  - pip install cpp-coveralls --user
  - export LD_LIBRARY_PATH=$PWD/build/dist/lib:$LD_LIBRARY_PATH
env:
  - USE_CONTEXT=ON
  - USE_CONTEXT=OFF
matrix:
  exclude:
    - compiler: gcc
      env: USE_CONTEXT=OFF
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
    - libssl-dev
    - cmake
    - cmake-data
script:
  - pwd
  - git clone git://github.com/cose-wg/Examples Examples
  - ls
  - mkdir build
  - cd build && cmake -Duse_context=$USE_CONTEXT -Dcoveralls_send=ON .. && make all test
  - ls
  - ls /home/travis
  - ls Examples
  - make coveralls


