language: c
compiler:
  - gcc
before_install:
  - sudo pip install cpp-coveralls
addons:
  apt:
    packages:
    - cmake
    - cmake-data
    - libssl-dev
script:
  - mkdir build
  - cd build && cmake .. && make all test
  - make coveralls


